steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/gcloud-lite/gcloud-go']
- name: us-west1-docker.pkg.dev/$PROJECT_ID/tonym-us/gcloud-go-release
  secretEnv: ['GH_TOKEN']
images:
- 'us-west1-docker.pkg.dev/$PROJECT_ID/gcloud-lite/gcloud-go'
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/GH_TOKEN/versions/1
    env: 'GH_TOKEN'
tags: ['latest']