steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/gcloud-lite/gcloud-go']
images:
- 'us-west1-docker.pkg.dev/$PROJECT_ID/gcloud-lite/gcloud-go'
tags: ['latest']